[project]
name = "dbcrafter"
version = "0.1.0"
dependencies = [
    "pyqt6",
    "pyparsing"
]

[tool.setuptools.packages.find]
exclude = ["dbcrafter.test*"]  # empty by default

#add launcher scripts
[project.scripts]
dbcrafter = "dbcrafter.backend.gui.dbml_gui_launcher:main"